# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lottery.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(910, 655)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(Main)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_r00 = MyLabel(Main)
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(30)
        self.label_r00.setFont(font)
        self.label_r00.setStyleSheet("border:1px solid black;border-radius:5px")
        self.label_r00.setAlignment(QtCore.Qt.AlignCenter)
        self.label_r00.setObjectName("label_r00")
        self.horizontalLayout.addWidget(self.label_r00)
        self.label_r01 = MyLabel(Main)
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(30)
        self.label_r01.setFont(font)
        self.label_r01.setStyleSheet("border:1px solid black;border-radius:5px")
        self.label_r01.setTextFormat(QtCore.Qt.AutoText)
        self.label_r01.setAlignment(QtCore.Qt.AlignCenter)
        self.label_r01.setObjectName("label_r01")
        self.horizontalLayout.addWidget(self.label_r01)
        self.label_r02 = MyLabel(Main)
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(30)
        self.label_r02.setFont(font)
        self.label_r02.setStyleSheet("border:1px solid black;border-radius:5px")
        self.label_r02.setTextFormat(QtCore.Qt.AutoText)
        self.label_r02.setAlignment(QtCore.Qt.AlignCenter)
        self.label_r02.setObjectName("label_r02")
        self.horizontalLayout.addWidget(self.label_r02)
        self.label_r03 = MyLabel(Main)
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(30)
        self.label_r03.setFont(font)
        self.label_r03.setStyleSheet("border:1px solid black;border-radius:5px")
        self.label_r03.setTextFormat(QtCore.Qt.AutoText)
        self.label_r03.setAlignment(QtCore.Qt.AlignCenter)
        self.label_r03.setObjectName("label_r03")
        self.horizontalLayout.addWidget(self.label_r03)
        self.label_r04 = MyLabel(Main)
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(30)
        self.label_r04.setFont(font)
        self.label_r04.setStyleSheet("border:1px solid black;border-radius:5px")
        self.label_r04.setTextFormat(QtCore.Qt.AutoText)
        self.label_r04.setAlignment(QtCore.Qt.AlignCenter)
        self.label_r04.setObjectName("label_r04")
        self.horizontalLayout.addWidget(self.label_r04)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_r11 = MyLabel(Main)
        self.label_r11.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(30)
        self.label_r11.setFont(font)
        self.label_r11.setStyleSheet("border:1px solid black;border-radius:5px")
        self.label_r11.setTextFormat(QtCore.Qt.AutoText)
        self.label_r11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_r11.setObjectName("label_r11")
        self.verticalLayout_2.addWidget(self.label_r11)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.label = QtWidgets.QLabel(Main)
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.pushButton = QtWidgets.QPushButton(Main)
        self.pushButton.setMaximumSize(QtCore.QSize(500, 501))
        self.pushButton.setBaseSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(42)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_3.addWidget(self.pushButton)
        self.label_2 = QtWidgets.QLabel(Main)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_r05 = MyLabel(Main)
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(30)
        self.label_r05.setFont(font)
        self.label_r05.setStyleSheet("border:1px solid black;border-radius:5px")
        self.label_r05.setTextFormat(QtCore.Qt.AutoText)
        self.label_r05.setAlignment(QtCore.Qt.AlignCenter)
        self.label_r05.setObjectName("label_r05")
        self.verticalLayout.addWidget(self.label_r05)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_r10 = MyLabel(Main)
        self.label_r10.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(30)
        self.label_r10.setFont(font)
        self.label_r10.setStyleSheet("border:1px solid black;border-radius:5px")
        self.label_r10.setTextFormat(QtCore.Qt.AutoText)
        self.label_r10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_r10.setObjectName("label_r10")
        self.horizontalLayout_2.addWidget(self.label_r10)
        self.label_r09 = MyLabel(Main)
        self.label_r09.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(30)
        self.label_r09.setFont(font)
        self.label_r09.setStyleSheet("border:1px solid black;border-radius:5px")
        self.label_r09.setTextFormat(QtCore.Qt.AutoText)
        self.label_r09.setAlignment(QtCore.Qt.AlignCenter)
        self.label_r09.setObjectName("label_r09")
        self.horizontalLayout_2.addWidget(self.label_r09)
        self.label_r08 = MyLabel(Main)
        self.label_r08.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(30)
        self.label_r08.setFont(font)
        self.label_r08.setStyleSheet("border:1px solid black;border-radius:5px")
        self.label_r08.setTextFormat(QtCore.Qt.AutoText)
        self.label_r08.setAlignment(QtCore.Qt.AlignCenter)
        self.label_r08.setObjectName("label_r08")
        self.horizontalLayout_2.addWidget(self.label_r08)
        self.label_r07 = MyLabel(Main)
        self.label_r07.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(30)
        self.label_r07.setFont(font)
        self.label_r07.setStyleSheet("border:1px solid black;border-radius:5px")
        self.label_r07.setTextFormat(QtCore.Qt.AutoText)
        self.label_r07.setAlignment(QtCore.Qt.AlignCenter)
        self.label_r07.setObjectName("label_r07")
        self.horizontalLayout_2.addWidget(self.label_r07)
        self.label_r06 = MyLabel(Main)
        self.label_r06.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(30)
        self.label_r06.setFont(font)
        self.label_r06.setStyleSheet("border:1px solid black;border-radius:5px")
        self.label_r06.setTextFormat(QtCore.Qt.AutoText)
        self.label_r06.setAlignment(QtCore.Qt.AlignCenter)
        self.label_r06.setObjectName("label_r06")
        self.horizontalLayout_2.addWidget(self.label_r06)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_p1 = QtWidgets.QLabel(Main)
        self.label_p1.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(16)
        self.label_p1.setFont(font)
        self.label_p1.setObjectName("label_p1")
        self.horizontalLayout_5.addWidget(self.label_p1)
        self.label_p2 = QtWidgets.QLabel(Main)
        self.label_p2.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(16)
        self.label_p2.setFont(font)
        self.label_p2.setObjectName("label_p2")
        self.horizontalLayout_5.addWidget(self.label_p2)
        self.label_p3 = QtWidgets.QLabel(Main)
        self.label_p3.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(16)
        self.label_p3.setFont(font)
        self.label_p3.setObjectName("label_p3")
        self.horizontalLayout_5.addWidget(self.label_p3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_p4 = QtWidgets.QLabel(Main)
        self.label_p4.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(16)
        self.label_p4.setFont(font)
        self.label_p4.setObjectName("label_p4")
        self.horizontalLayout_4.addWidget(self.label_p4)
        self.label_p5 = QtWidgets.QLabel(Main)
        self.label_p5.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(16)
        self.label_p5.setFont(font)
        self.label_p5.setObjectName("label_p5")
        self.horizontalLayout_4.addWidget(self.label_p5)
        self.label_p6 = QtWidgets.QLabel(Main)
        self.label_p6.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(16)
        self.label_p6.setFont(font)
        self.label_p6.setObjectName("label_p6")
        self.horizontalLayout_4.addWidget(self.label_p6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6.addLayout(self.verticalLayout_3)
        self.textEdit = QtWidgets.QTextEdit(Main)
        self.textEdit.setMaximumSize(QtCore.QSize(350, 16777215))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(14)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout_6.addWidget(self.textEdit)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_6)

        self.retranslateUi(Main)
        self.pushButton.clicked.connect(Main.lottery_start)
        self.label_r00.label_double_click.connect(Main.label_doubl_cleck)
        self.label_r01.label_double_click.connect(Main.label_doubl_cleck)
        self.label_r02.label_double_click.connect(Main.label_doubl_cleck)
        self.label_r08.label_double_click.connect(Main.label_doubl_cleck)
        self.label_r03.label_double_click.connect(Main.label_doubl_cleck)
        self.label_r05.label_double_click.connect(Main.label_doubl_cleck)
        self.label_r04.label_double_click.connect(Main.label_doubl_cleck)
        self.label_r06.label_double_click.connect(Main.label_doubl_cleck)
        self.label_r07.label_double_click.connect(Main.label_doubl_cleck)
        self.label_r08.label_double_click.connect(Main.label_doubl_cleck)
        self.label_r09.label_double_click.connect(Main.label_doubl_cleck)
        self.label_r10.label_double_click.connect(Main.label_doubl_cleck)
        self.label_r11.label_double_click.connect(Main.label_doubl_cleck)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "Form"))
        self.label_r00.setText(_translate("Main", "三等奖"))
        self.label_r01.setText(_translate("Main", "幸运奖"))
        self.label_r02.setText(_translate("Main", "特等奖"))
        self.label_r03.setText(_translate("Main", "二等奖"))
        self.label_r04.setText(_translate("Main", "幸运奖"))
        self.label_r11.setText(_translate("Main", "四等奖"))
        self.pushButton.setText(_translate("Main", "点击抽奖"))
        self.label_r05.setText(_translate("Main", "一等奖"))
        self.label_r10.setText(_translate("Main", "四等奖"))
        self.label_r09.setText(_translate("Main", "四等奖"))
        self.label_r08.setText(_translate("Main", "四等奖"))
        self.label_r07.setText(_translate("Main", "四等奖"))
        self.label_r06.setText(_translate("Main", "四等奖"))
        self.label_p1.setText(_translate("Main", "特等奖：1"))
        self.label_p2.setText(_translate("Main", "一等奖：2"))
        self.label_p3.setText(_translate("Main", "三等奖：4"))
        self.label_p4.setText(_translate("Main", "四等奖：5"))
        self.label_p5.setText(_translate("Main", "五等奖：10"))
        self.label_p6.setText(_translate("Main", "幸运奖：5000"))

from mylabel import MyLabel
