# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'lottery.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Main(object):
    def setupUi(self, Main):
        Main.setObjectName("Main")
        Main.resize(797, 645)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(Main)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_r1 = QtWidgets.QLabel(Main)
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(16)
        self.label_r1.setFont(font)
        self.label_r1.setStyleSheet("border:1px solid black;border-radius:5px")
        self.label_r1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_r1.setObjectName("label_r1")
        self.horizontalLayout_3.addWidget(self.label_r1)
        self.label_r2 = QtWidgets.QLabel(Main)
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(16)
        self.label_r2.setFont(font)
        self.label_r2.setStyleSheet("border:1px solid black;border-radius:5px")
        self.label_r2.setTextFormat(QtCore.Qt.AutoText)
        self.label_r2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_r2.setObjectName("label_r2")
        self.horizontalLayout_3.addWidget(self.label_r2)
        self.label_r3 = QtWidgets.QLabel(Main)
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(16)
        self.label_r3.setFont(font)
        self.label_r3.setStyleSheet("border:1px solid black;border-radius:5px")
        self.label_r3.setTextFormat(QtCore.Qt.AutoText)
        self.label_r3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_r3.setObjectName("label_r3")
        self.horizontalLayout_3.addWidget(self.label_r3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_r8 = QtWidgets.QLabel(Main)
        self.label_r8.setMinimumSize(QtCore.QSize(0, 78))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(16)
        self.label_r8.setFont(font)
        self.label_r8.setStyleSheet("border:1px solid black;border-radius:5px")
        self.label_r8.setTextFormat(QtCore.Qt.AutoText)
        self.label_r8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_r8.setObjectName("label_r8")
        self.horizontalLayout_4.addWidget(self.label_r8)
        self.pushButton = QtWidgets.QPushButton(Main)
        self.pushButton.setMaximumSize(QtCore.QSize(16777215, 500))
        self.pushButton.setBaseSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_4.addWidget(self.pushButton)
        self.label_r4 = QtWidgets.QLabel(Main)
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(16)
        self.label_r4.setFont(font)
        self.label_r4.setStyleSheet("border:1px solid black;border-radius:5px")
        self.label_r4.setTextFormat(QtCore.Qt.AutoText)
        self.label_r4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_r4.setObjectName("label_r4")
        self.horizontalLayout_4.addWidget(self.label_r4)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_r7 = QtWidgets.QLabel(Main)
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(16)
        self.label_r7.setFont(font)
        self.label_r7.setStyleSheet("border:1px solid black;border-radius:5px")
        self.label_r7.setTextFormat(QtCore.Qt.AutoText)
        self.label_r7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_r7.setObjectName("label_r7")
        self.horizontalLayout_5.addWidget(self.label_r7)
        self.label_r6 = QtWidgets.QLabel(Main)
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(16)
        self.label_r6.setFont(font)
        self.label_r6.setStyleSheet("border:1px solid black;border-radius:5px")
        self.label_r6.setTextFormat(QtCore.Qt.AutoText)
        self.label_r6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_r6.setObjectName("label_r6")
        self.horizontalLayout_5.addWidget(self.label_r6)
        self.label_r5 = QtWidgets.QLabel(Main)
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(16)
        self.label_r5.setFont(font)
        self.label_r5.setStyleSheet("border:1px solid black;border-radius:5px")
        self.label_r5.setTextFormat(QtCore.Qt.AutoText)
        self.label_r5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_r5.setObjectName("label_r5")
        self.horizontalLayout_5.addWidget(self.label_r5)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_p1 = QtWidgets.QLabel(Main)
        self.label_p1.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(16)
        self.label_p1.setFont(font)
        self.label_p1.setObjectName("label_p1")
        self.horizontalLayout.addWidget(self.label_p1)
        self.label_p2 = QtWidgets.QLabel(Main)
        self.label_p2.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(16)
        self.label_p2.setFont(font)
        self.label_p2.setObjectName("label_p2")
        self.horizontalLayout.addWidget(self.label_p2)
        self.label_p3 = QtWidgets.QLabel(Main)
        self.label_p3.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(16)
        self.label_p3.setFont(font)
        self.label_p3.setObjectName("label_p3")
        self.horizontalLayout.addWidget(self.label_p3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_p4 = QtWidgets.QLabel(Main)
        self.label_p4.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(16)
        self.label_p4.setFont(font)
        self.label_p4.setObjectName("label_p4")
        self.horizontalLayout_2.addWidget(self.label_p4)
        self.label_p5 = QtWidgets.QLabel(Main)
        self.label_p5.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(16)
        self.label_p5.setFont(font)
        self.label_p5.setObjectName("label_p5")
        self.horizontalLayout_2.addWidget(self.label_p5)
        self.label_p6 = QtWidgets.QLabel(Main)
        self.label_p6.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(16)
        self.label_p6.setFont(font)
        self.label_p6.setObjectName("label_p6")
        self.horizontalLayout_2.addWidget(self.label_p6)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.horizontalLayout_6.addLayout(self.verticalLayout_3)
        self.textEdit = QtWidgets.QTextEdit(Main)
        self.textEdit.setMaximumSize(QtCore.QSize(350, 16777215))
        font = QtGui.QFont()
        font.setFamily("仿宋")
        font.setPointSize(14)
        self.textEdit.setFont(font)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout_6.addWidget(self.textEdit)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_6)

        self.retranslateUi(Main)
        self.pushButton.clicked.connect(Main.lottery_start)
        QtCore.QMetaObject.connectSlotsByName(Main)

    def retranslateUi(self, Main):
        _translate = QtCore.QCoreApplication.translate
        Main.setWindowTitle(_translate("Main", "Form"))
        self.label_r1.setText(_translate("Main", "三等奖"))
        self.label_r2.setText(_translate("Main", "幸运奖"))
        self.label_r3.setText(_translate("Main", "特等奖"))
        self.label_r8.setText(_translate("Main", "四等奖"))
        self.pushButton.setText(_translate("Main", "PushButton"))
        self.label_r4.setText(_translate("Main", "二等奖"))
        self.label_r7.setText(_translate("Main", "幸运奖"))
        self.label_r6.setText(_translate("Main", "一等奖"))
        self.label_r5.setText(_translate("Main", "幸运奖"))
        self.label_p1.setText(_translate("Main", "特等奖：1"))
        self.label_p2.setText(_translate("Main", "一等奖：2"))
        self.label_p3.setText(_translate("Main", "三等奖：4"))
        self.label_p4.setText(_translate("Main", "四等奖：5"))
        self.label_p5.setText(_translate("Main", "五等奖：10"))
        self.label_p6.setText(_translate("Main", "幸运奖：5000"))

