# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'prize_pool_set.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Prize_Pool_Set(object):
    def setupUi(self, Prize_Pool_Set):
        Prize_Pool_Set.setObjectName("Prize_Pool_Set")
        Prize_Pool_Set.resize(640, 480)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(Prize_Pool_Set)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_4 = QtWidgets.QLabel(Prize_Pool_Set)
        self.label_4.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.label_2 = QtWidgets.QLabel(Prize_Pool_Set)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(Prize_Pool_Set)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(Prize_Pool_Set)
        self.label.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lineEdit_c0 = QtWidgets.QLineEdit(Prize_Pool_Set)
        self.lineEdit_c0.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lineEdit_c0.setObjectName("lineEdit_c0")
        self.horizontalLayout_2.addWidget(self.lineEdit_c0)
        self.lineEdit_r0 = QtWidgets.QLineEdit(Prize_Pool_Set)
        self.lineEdit_r0.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lineEdit_r0.setObjectName("lineEdit_r0")
        self.horizontalLayout_2.addWidget(self.lineEdit_r0)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(Prize_Pool_Set)
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.lineEdit_c1 = QtWidgets.QLineEdit(Prize_Pool_Set)
        self.lineEdit_c1.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lineEdit_c1.setObjectName("lineEdit_c1")
        self.horizontalLayout_3.addWidget(self.lineEdit_c1)
        self.lineEdit_r1 = QtWidgets.QLineEdit(Prize_Pool_Set)
        self.lineEdit_r1.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lineEdit_r1.setObjectName("lineEdit_r1")
        self.horizontalLayout_3.addWidget(self.lineEdit_r1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(Prize_Pool_Set)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.lineEdit_c2 = QtWidgets.QLineEdit(Prize_Pool_Set)
        self.lineEdit_c2.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lineEdit_c2.setObjectName("lineEdit_c2")
        self.horizontalLayout_4.addWidget(self.lineEdit_c2)
        self.lineEdit_r2 = QtWidgets.QLineEdit(Prize_Pool_Set)
        self.lineEdit_r2.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lineEdit_r2.setObjectName("lineEdit_r2")
        self.horizontalLayout_4.addWidget(self.lineEdit_r2)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(Prize_Pool_Set)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.lineEdit_c3 = QtWidgets.QLineEdit(Prize_Pool_Set)
        self.lineEdit_c3.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lineEdit_c3.setObjectName("lineEdit_c3")
        self.horizontalLayout_5.addWidget(self.lineEdit_c3)
        self.lineEdit_r3 = QtWidgets.QLineEdit(Prize_Pool_Set)
        self.lineEdit_r3.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lineEdit_r3.setObjectName("lineEdit_r3")
        self.horizontalLayout_5.addWidget(self.lineEdit_r3)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_8 = QtWidgets.QLabel(Prize_Pool_Set)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.lineEdit_c4 = QtWidgets.QLineEdit(Prize_Pool_Set)
        self.lineEdit_c4.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lineEdit_c4.setObjectName("lineEdit_c4")
        self.horizontalLayout_6.addWidget(self.lineEdit_c4)
        self.lineEdit_r4 = QtWidgets.QLineEdit(Prize_Pool_Set)
        self.lineEdit_r4.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lineEdit_r4.setObjectName("lineEdit_r4")
        self.horizontalLayout_6.addWidget(self.lineEdit_r4)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_9 = QtWidgets.QLabel(Prize_Pool_Set)
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_7.addWidget(self.label_9)
        self.lineEdit_c5 = QtWidgets.QLineEdit(Prize_Pool_Set)
        self.lineEdit_c5.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lineEdit_c5.setObjectName("lineEdit_c5")
        self.horizontalLayout_7.addWidget(self.lineEdit_c5)
        self.lineEdit_r5 = QtWidgets.QLineEdit(Prize_Pool_Set)
        self.lineEdit_r5.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lineEdit_r5.setObjectName("lineEdit_r5")
        self.horizontalLayout_7.addWidget(self.lineEdit_r5)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_10 = QtWidgets.QLabel(Prize_Pool_Set)
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_8.addWidget(self.label_10)
        self.lineEdit_c6 = QtWidgets.QLineEdit(Prize_Pool_Set)
        self.lineEdit_c6.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lineEdit_c6.setObjectName("lineEdit_c6")
        self.horizontalLayout_8.addWidget(self.lineEdit_c6)
        self.lineEdit_r6 = QtWidgets.QLineEdit(Prize_Pool_Set)
        self.lineEdit_r6.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lineEdit_r6.setObjectName("lineEdit_r6")
        self.horizontalLayout_8.addWidget(self.lineEdit_r6)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_11 = QtWidgets.QLabel(Prize_Pool_Set)
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_9.addWidget(self.label_11)
        self.lineEdit_c7 = QtWidgets.QLineEdit(Prize_Pool_Set)
        self.lineEdit_c7.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lineEdit_c7.setObjectName("lineEdit_c7")
        self.horizontalLayout_9.addWidget(self.lineEdit_c7)
        self.lineEdit_r7 = QtWidgets.QLineEdit(Prize_Pool_Set)
        self.lineEdit_r7.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lineEdit_r7.setObjectName("lineEdit_r7")
        self.horizontalLayout_9.addWidget(self.lineEdit_r7)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_15 = QtWidgets.QLabel(Prize_Pool_Set)
        self.label_15.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_10.addWidget(self.label_15)
        self.lineEdit_c8 = QtWidgets.QLineEdit(Prize_Pool_Set)
        self.lineEdit_c8.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lineEdit_c8.setObjectName("lineEdit_c8")
        self.horizontalLayout_10.addWidget(self.lineEdit_c8)
        self.lineEdit_r8 = QtWidgets.QLineEdit(Prize_Pool_Set)
        self.lineEdit_r8.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lineEdit_r8.setObjectName("lineEdit_r8")
        self.horizontalLayout_10.addWidget(self.lineEdit_r8)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_12 = QtWidgets.QLabel(Prize_Pool_Set)
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_11.addWidget(self.label_12)
        self.lineEdit_c9 = QtWidgets.QLineEdit(Prize_Pool_Set)
        self.lineEdit_c9.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lineEdit_c9.setObjectName("lineEdit_c9")
        self.horizontalLayout_11.addWidget(self.lineEdit_c9)
        self.lineEdit_r9 = QtWidgets.QLineEdit(Prize_Pool_Set)
        self.lineEdit_r9.setMaximumSize(QtCore.QSize(16777215, 25))
        self.lineEdit_r9.setObjectName("lineEdit_r9")
        self.horizontalLayout_11.addWidget(self.lineEdit_r9)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_13 = QtWidgets.QLabel(Prize_Pool_Set)
        self.label_13.setText("")
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_12.addWidget(self.label_13)
        self.pushButton = QtWidgets.QPushButton(Prize_Pool_Set)
        self.pushButton.setMaximumSize(QtCore.QSize(80, 16777215))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_12.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13.addLayout(self.verticalLayout)

        self.retranslateUi(Prize_Pool_Set)
        self.pushButton.clicked.connect(Prize_Pool_Set.save)
        QtCore.QMetaObject.connectSlotsByName(Prize_Pool_Set)

    def retranslateUi(self, Prize_Pool_Set):
        _translate = QtCore.QCoreApplication.translate
        Prize_Pool_Set.setWindowTitle(_translate("Prize_Pool_Set", "Form"))
        self.label_4.setText(_translate("Prize_Pool_Set", "奖项等级"))
        self.label_2.setText(_translate("Prize_Pool_Set", "数量"))
        self.label_3.setText(_translate("Prize_Pool_Set", "范围"))
        self.label.setText(_translate("Prize_Pool_Set", "特等奖"))
        self.label_5.setText(_translate("Prize_Pool_Set", "一等奖"))
        self.label_6.setText(_translate("Prize_Pool_Set", "二等奖"))
        self.label_7.setText(_translate("Prize_Pool_Set", "三等奖"))
        self.label_8.setText(_translate("Prize_Pool_Set", "四等奖"))
        self.label_9.setText(_translate("Prize_Pool_Set", "五等奖"))
        self.label_10.setText(_translate("Prize_Pool_Set", "六等奖"))
        self.label_11.setText(_translate("Prize_Pool_Set", "七等奖"))
        self.label_15.setText(_translate("Prize_Pool_Set", "八等奖"))
        self.label_12.setText(_translate("Prize_Pool_Set", "幸运奖"))
        self.pushButton.setText(_translate("Prize_Pool_Set", "保  存"))

